import type { Trail, TrailWinery, Winery, Wine, WineryHours, RewardTier, WineryEvent } from "./types";
import { feetToMeters } from "./geo";

/**
 * Local fallback content for the Founding Trail.
 *
 * This is used when Supabase isn't configured (local dev, previews without
 * secrets) so the app is always demoable, and doubles as the source data for
 * `supabase/seed.sql`. Once Supabase is connected, `src/lib/data.ts` reads
 * from the database instead and this file is no longer on the hot path.
 *
 * Coordinates are approximate town-center placeholders — replace with each
 * winery's verified tasting-room GPS pin via the admin dashboard before
 * relying on check-in geofencing in production.
 */

export const FOUNDING_TRAIL: Trail = {
  id: "trail-founding",
  name: "Tennessee Wine Trails — Founding Trail",
  slug: "founding-trail",
  description:
    "The original four stops of the Tennessee Wine Trails: a countryside tour through Middle Tennessee's boutique wineries.",
  image: null,
  active: true,
  created_at: "2026-01-01T00:00:00.000Z",
};

export const SEED_WINERIES: Winery[] = [
  {
    id: "winery-arrington",
    name: "Arrington Vineyards",
    slug: "arrington-vineyards",
    city: "Arrington",
    state: "Tennessee",
    address: "6211 Patton Rd, Arrington, TN 37014",
    latitude: 35.7623,
    longitude: -86.6614,
    description:
      "Rolling hillside vineyards in the heart of Williamson County, known for relaxed picnic-style tastings and live music among the vines.",
    hero_image: "",
    logo_mark: null,
    website_url: "https://arringtonvineyards.com",
    wine_club_url: "https://arringtonvineyards.com/wine-club",
    wine_club_title: "Uncorked Club",
    wine_club_description:
      "A quarterly taste of what's new in the barrel room, delivered to your door.",
    wine_club_benefits: [
      "Exclusive small-batch releases",
      "Member-only events on the hillside",
      "Preferred member pricing",
      "Discounts on bottle purchases",
    ],
    hours:
      "Mon–Thu 11am–8pm · Fri 11am–9pm · Sat 11am–8pm · Sun 12pm–8pm (Apr–Oct; shorter hours Nov–Mar)",
    phone: null,
    instagram_url: "https://instagram.com",
    facebook_url: "https://facebook.com",
    checkin_radius_meters: Math.round(feetToMeters(750)),
    wine_menu_url: null,
    events_page_url: null,
    yelp_url: "https://www.yelp.com/biz/arrington-vineyards-arrington",
    active: true,
    sort_order: 1,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "winery-woodfeather",
    name: "Woodfeather Farm Vineyard & Winery",
    slug: "woodfeather-farm",
    city: "Chapel Hill",
    state: "Tennessee",
    address: "106 N Horton Pkwy, Chapel Hill, TN 37034",
    latitude: 35.6337,
    longitude: -86.6903,
    description:
      "A working family farm turned vineyard, pouring estate wines with a warm, unhurried farmhouse welcome.",
    hero_image: "",
    logo_mark: null,
    website_url: "https://www.woodfeatherfarm.com",
    wine_club_url: "https://example.com/woodfeather/wine-club",
    wine_club_title: "Woodfeather Wine Club",
    wine_club_description: "Take a little of Woodfeather home with you, season after season.",
    wine_club_benefits: [
      "Exclusive releases",
      "Member events",
      "Member pricing",
      "Bottle discounts",
    ],
    hours: "Closed Mon–Wed · Thu 2pm–8pm · Fri–Sat 1pm–9pm · Sun 1pm–6pm",
    phone: null,
    instagram_url: "https://instagram.com",
    facebook_url: "https://facebook.com",
    checkin_radius_meters: Math.round(feetToMeters(750)),
    wine_menu_url: "https://www.woodfeatherfarm.com/shop/",
    events_page_url: null,
    yelp_url: "https://www.yelp.com/biz/woodfeather-farm-chapel-hill-2",
    active: true,
    sort_order: 2,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "winery-pickers-creek",
    name: "Picker's Creek Winery",
    slug: "pickers-creek",
    city: "Lewisburg",
    state: "Tennessee",
    address: "1986 New Columbia Hwy, Lewisburg, TN 37091",
    latitude: 35.4495,
    longitude: -86.7911,
    description:
      "A creekside tasting room pouring approachable Southern wines, named for the old cotton-picking trails that once crossed the property.",
    hero_image: "",
    logo_mark: null,
    website_url: "https://www.pickerscreekwinery.com",
    wine_club_url: "https://example.com/pickers-creek/wine-club",
    wine_club_title: "Creekside Club",
    wine_club_description: "Seasonal pours and member-first access, straight from the creek.",
    wine_club_benefits: [
      "Exclusive releases",
      "Member events",
      "Member pricing",
      "Bottle discounts",
    ],
    hours: "Closed Mon–Thu · Fri 11am–8pm (until 9pm w/ live music) · Sat 11am–9pm · Sun 12pm–6pm",
    phone: null,
    instagram_url: "https://instagram.com",
    facebook_url: "https://facebook.com",
    checkin_radius_meters: Math.round(feetToMeters(750)),
    wine_menu_url: "https://www.pickerscreekwinery.com/wines/",
    events_page_url: null,
    yelp_url: "https://www.yelp.com/biz/pickers-creek-winery-lewisburg",
    active: true,
    sort_order: 3,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "winery-grinders-switch",
    name: "Grinder's Switch Winery",
    slug: "grinders-switch",
    city: "Columbia",
    state: "Tennessee",
    address: "510 North Garden Street, Suite D, Columbia, TN 38401",
    latitude: 35.6151,
    longitude: -87.0353,
    description:
      "Named for the historic rail switch that once ran through Hickman County, this Maury County tasting lounge — set in a converted 1950s tire shop — pours bold reds in a warm, unpretentious setting.",
    hero_image: "",
    logo_mark: null,
    website_url: "https://gswinery.com",
    wine_club_url: "https://gswinery.com/wine-clubs/",
    wine_club_title: "Grinder's Switch Wine Club",
    wine_club_description:
      "No membership fee — choose 3, 6, or 12 bottles of dry, sweet, or mixed wines each shipment, delivered quarterly or bi-monthly with Club 60.",
    wine_club_benefits: [
      "No membership fee",
      "15% off wine, 20% off merch anytime",
      "Free shipping on every shipment",
      "Complimentary tastings & member gifts",
    ],
    hours: "Closed Mon · Tue–Fri 3pm–8pm · Sat 11am–7pm · Sun 1pm–7pm",
    phone: null,
    instagram_url: "https://instagram.com",
    facebook_url: "https://facebook.com",
    checkin_radius_meters: Math.round(feetToMeters(750)),
    wine_menu_url: "https://gswinery.com/our-wines/",
    events_page_url: null,
    yelp_url: "https://www.yelp.com/biz/grinders-switch-winery-columbia",
    active: true,
    sort_order: 4,
    created_at: "2026-01-01T00:00:00.000Z",
  },
];

export const SEED_TRAIL_WINERIES: TrailWinery[] = SEED_WINERIES.map((w, i) => ({
  id: `tw-${w.slug}`,
  trail_id: FOUNDING_TRAIL.id,
  winery_id: w.id,
  display_order: i + 1,
}));

/**
 * A small tasting flight per winery, drawn from each winery's actual
 * published wine names/varietals where publicly available (Arrington,
 * Picker's Creek, Grinder's Switch). Woodfeather Farm doesn't list specific
 * bottle names publicly, so its two wines are named for the real estate
 * grape varieties they grow (Chambourcin, Vidal Blanc) rather than an
 * invented brand name. Tasting notes are written from each grape's real
 * characteristics and any published description found — still worth
 * replacing with each winery's official copy via the admin dashboard.
 */
export const SEED_WINES: Wine[] = [
  {
    id: "wine-arrington-scarlet",
    winery_id: "winery-arrington",
    name: "Scarlet",
    slug: "arrington-scarlet",
    varietal: "Chambourcin",
    style: "rose",
    tasting_notes:
      "Arrington's signature pour: estate-grown Chambourcin pressed rosé-style, with bright red berry and a refreshing, off-dry finish.",
    food_pairing: "Grilled salmon or a summer charcuterie board",
    sold_out: false,
    active: true,
    sort_order: 1,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-chardonnay",
    winery_id: "winery-arrington",
    name: "Chardonnay",
    slug: "arrington-chardonnay",
    varietal: "Chardonnay",
    style: "white",
    tasting_notes: "Bright and food-friendly, with green apple, citrus, and a clean, crisp finish.",
    food_pairing: "Roast chicken or creamy pasta",
    sold_out: false,
    active: true,
    sort_order: 2,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-riesling",
    winery_id: "winery-arrington",
    name: "Riesling",
    slug: "arrington-riesling",
    varietal: "Riesling",
    style: "sweet",
    tasting_notes: "Off-dry and floral, with ripe stone fruit and a crisp mineral finish.",
    food_pairing: "Spicy Thai food or a fruit tart",
    sold_out: false,
    active: true,
    sort_order: 3,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-cabernet",
    winery_id: "winery-arrington",
    name: "Cabernet Sauvignon",
    slug: "arrington-cabernet-sauvignon",
    varietal: "Cabernet Sauvignon",
    style: "red",
    tasting_notes: "Structured and dry, with dark currant, cedar, and firm tannins.",
    food_pairing: "Grilled steak or aged cheddar",
    sold_out: false,
    active: true,
    sort_order: 4,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-red-fox-red",
    winery_id: "winery-arrington",
    name: "Red Fox Red",
    slug: "arrington-red-fox-red",
    varietal: "Sangiovese, Petit Verdot & Chambourcin",
    style: "red",
    tasting_notes:
      "A bold field blend of Sangiovese, Petit Verdot, and Chambourcin, rounded out with a whisper of Viognier.",
    food_pairing: "Braised short ribs or a hearty stew",
    sold_out: false,
    active: true,
    sort_order: 5,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-working-dog",
    winery_id: "winery-woodfeather",
    name: "Working Dog",
    slug: "woodfeather-working-dog",
    varietal: "Red Blend",
    style: "red",
    tasting_notes:
      "A bourbon barrel-aged red with dark fruit, vanilla, and toasted oak — as sturdy as its name.",
    food_pairing: "Smoked brisket or dark chocolate",
    sold_out: false,
    active: true,
    sort_order: 1,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-terrier-rosato",
    winery_id: "winery-woodfeather",
    name: "Terrier Rosato",
    slug: "woodfeather-terrier-rosato",
    varietal: "Vidal Blanc & Sunbelt Blend",
    style: "rose",
    tasting_notes:
      "A blend of Tennessee Vidal Blanc and Sunbelt, reflecting the lively spirit of the Terrier — bright peach, honeysuckle, and stone fruit with subtle oak spice and vanilla. Crisp yet smooth, with a refreshing, spirited finish.",
    food_pairing: "Goat cheese salad or grilled shrimp",
    sold_out: false,
    active: true,
    sort_order: 2,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-papillon-blanc",
    winery_id: "winery-woodfeather",
    name: "Papillon Blanc",
    slug: "woodfeather-papillon-blanc",
    varietal: "White Blend",
    style: "white",
    tasting_notes: "Oak-aged and elegant, with baked apple, vanilla, and a rounded, creamy finish.",
    food_pairing: "Roast pork or buttered lobster",
    sold_out: false,
    active: true,
    sort_order: 3,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-herding-dog",
    winery_id: "winery-woodfeather",
    name: "Herding Dog Red Blend",
    slug: "woodfeather-herding-dog-red-blend",
    varietal: "Red Blend",
    style: "red",
    tasting_notes: "An easy-drinking red blend of estate varietals, soft tannins and ripe berry fruit.",
    food_pairing: "Burgers or a charcuterie board",
    sold_out: false,
    active: true,
    sort_order: 4,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-sporting-dog",
    winery_id: "winery-woodfeather",
    name: "Sporting Dog",
    slug: "woodfeather-sporting-dog",
    varietal: "Red Blend",
    style: "red",
    tasting_notes: "Oak-aged and full-bodied, with dark fruit, baking spice, and a long, smoky finish.",
    food_pairing: "Barbecue ribs or smoked gouda",
    sold_out: false,
    active: true,
    sort_order: 5,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-lagotto-romagnolo",
    winery_id: "winery-woodfeather",
    name: "Lagotto Romagnolo",
    slug: "woodfeather-lagotto-romagnolo",
    varietal: "Niagara & Enchantment Blend",
    style: "rose",
    tasting_notes:
      "Crafted from Tennessee Niagara and Enchantment, this rosé reflects the lively Lagotto Romagnolo — bright strawberry and melon with soft citrus and a hint of wildflower. Energetic, charming, and subtly earthy.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 6,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-coyote-jack",
    winery_id: "winery-woodfeather",
    name: "Coyote Jack",
    slug: "woodfeather-coyote-jack",
    varietal: "Apple",
    style: "sweet",
    tasting_notes:
      "Aged in a freshly emptied Leiper's Fork whiskey barrel, this apple wine channels the untamed spirit of the coyote and the legacy of early applejack. Crisp orchard apple deepens into caramel, spice, and toasted oak, finishing smooth and warm.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 7,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-blue-heeler",
    winery_id: "winery-woodfeather",
    name: "Blue Heeler Blueberry Dessert Wine",
    slug: "woodfeather-blue-heeler",
    varietal: "Blueberry & Blueberry Brandy Blend",
    style: "sweet",
    tasting_notes:
      "Like the loyal Blue Heeler it honors, this Tennessee dessert wine is bold yet balanced — a blend of estate blueberry wine and distilled blueberry brandy crafted with Leiper's Fork Distillery. Lush blueberry meets warm spirit and oak, finishing slightly sweet with a smooth, lingering finesse.",
    food_pairing: null,
    sold_out: true,
    active: true,
    sort_order: 8,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-maltese-bianco",
    winery_id: "winery-woodfeather",
    name: "Maltese Bianco",
    slug: "woodfeather-maltese-bianco",
    varietal: "Vidal Blanc & Niagara Blend",
    style: "white",
    tasting_notes:
      "Born from a Tennessee blend of Vidal Blanc and Niagara, this wine reflects the delicate charm of the Maltese — soft florals, crisp orchard fruit, and hints of peach, citrus, and honey. Clean, lively, and smooth.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 9,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-wolfhound-mead",
    winery_id: "winery-woodfeather",
    name: "Wolfhound Mead",
    slug: "woodfeather-wolfhound-mead",
    varietal: "Honey",
    style: "mead",
    tasting_notes: "A honey mead from Woodfeather Farm.",
    food_pairing: null,
    sold_out: true,
    active: true,
    sort_order: 10,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-woodfeather-wolfhound-dark",
    winery_id: "winery-woodfeather",
    name: "Wolfhound Dark — Coffee-Infused Honey Wine",
    slug: "woodfeather-wolfhound-dark",
    varietal: "Honey",
    style: "mead",
    tasting_notes: "A coffee-infused honey wine from Woodfeather Farm.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 11,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-pickers-creek-harmony",
    winery_id: "winery-pickers-creek",
    name: "Harmony",
    slug: "pickers-creek-harmony",
    varietal: "Chambourcin & Cabernet Sauvignon",
    style: "red",
    tasting_notes:
      "A Chambourcin and Cabernet Sauvignon blend — dark berry fruit with soft, easy-drinking tannins.",
    food_pairing: "Pulled pork or grilled sausage",
    sold_out: false,
    active: true,
    sort_order: 1,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-pickers-creek-peach",
    winery_id: "winery-pickers-creek",
    name: "Give Peach a Chance",
    slug: "pickers-creek-give-peach-a-chance",
    varietal: "Peach",
    style: "sweet",
    tasting_notes:
      "A playful, sun-ripened peach wine — juicy and sweet with a nostalgic, fruit-stand finish.",
    food_pairing: "Vanilla ice cream or a cheese plate",
    sold_out: false,
    active: true,
    sort_order: 2,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-pickers-creek-three-dog-white",
    winery_id: "winery-pickers-creek",
    name: "Three Dog White",
    slug: "pickers-creek-three-dog-white",
    varietal: "White Blend",
    style: "white",
    tasting_notes: "A crisp, easy-drinking white blend named for the porch dogs who inspired it.",
    food_pairing: "Fried catfish or a garden salad",
    sold_out: false,
    active: true,
    sort_order: 3,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-pickers-creek-rockabilly-red",
    winery_id: "winery-pickers-creek",
    name: "Rockabilly Red",
    slug: "pickers-creek-rockabilly-red",
    varietal: "Muscadine",
    style: "sweet",
    tasting_notes:
      "Made from Southern muscadine grapes — sweet, musky, and full of old-school Tennessee character.",
    food_pairing: "Barbecue or spicy wings",
    sold_out: false,
    active: true,
    sort_order: 4,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-pickers-creek-blackberry-blues",
    winery_id: "winery-pickers-creek",
    name: "Blackberry Blues",
    slug: "pickers-creek-blackberry-blues",
    varietal: "Blackberry",
    style: "sweet",
    tasting_notes: "A jammy blackberry fruit wine, deep purple and sweet down to the last sip.",
    food_pairing: "Dark chocolate or a cheese board",
    sold_out: false,
    active: true,
    sort_order: 5,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-grinders-switch-cabernet",
    winery_id: "winery-grinders-switch",
    name: "Cabernet Sauvignon",
    slug: "grinders-switch-cabernet-sauvignon",
    varietal: "Cabernet Sauvignon",
    style: "red",
    tasting_notes:
      "Bold and dry, with gripping tannins, leather, orange peel, and a hint of cracked pepper.",
    food_pairing: "Grilled steak or sharp cheddar",
    sold_out: false,
    active: true,
    sort_order: 1,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-grinders-switch-honeysuckle-rose",
    winery_id: "winery-grinders-switch",
    name: "Honeysuckle Rose",
    slug: "grinders-switch-honeysuckle-rose",
    varietal: "Blush Blend",
    style: "sweet",
    tasting_notes:
      "A gold medal-winning sweet blush, perfumed with honeysuckle and ripe stone fruit.",
    food_pairing: "Fresh fruit or a light salad",
    sold_out: false,
    active: true,
    sort_order: 2,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-grinders-switch-switch-red",
    winery_id: "winery-grinders-switch",
    name: "Switch Red",
    slug: "grinders-switch-switch-red",
    varietal: "Concord",
    style: "sweet",
    tasting_notes:
      "The best-seller: a sweet Concord red, juicy and jam-forward — welcome-mat wine.",
    food_pairing: "Barbecue or burgers",
    sold_out: false,
    active: true,
    sort_order: 3,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-grinders-switch-blondy",
    winery_id: "winery-grinders-switch",
    name: "Blondy",
    slug: "grinders-switch-blondy",
    varietal: "White Blend",
    style: "sweet",
    tasting_notes: "A gold medal sweet white, honeyed and smooth.",
    food_pairing: "Baked ham or fruit tart",
    sold_out: false,
    active: true,
    sort_order: 4,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-grinders-switch-blackberry-express",
    winery_id: "winery-grinders-switch",
    name: "Blackberry Express",
    slug: "grinders-switch-blackberry-express",
    varietal: "Blackberry",
    style: "sweet",
    tasting_notes: "A sweet blackberry fruit wine, bursting with ripe bramble and a syrupy finish.",
    food_pairing: "Vanilla cake or dark chocolate",
    sold_out: false,
    active: true,
    sort_order: 5,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-viognier",
    winery_id: "winery-arrington",
    name: "Viognier",
    slug: "arrington-viognier",
    varietal: "Viognier",
    style: "white",
    tasting_notes:
      "Pale yellow in color, with aromas of white peach and mango, and flavors of ripe pear, nectarine, and lime zest.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 6,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-honeysuckle",
    winery_id: "winery-arrington",
    name: "Honeysuckle",
    slug: "arrington-honeysuckle",
    varietal: "Gewürztraminer",
    style: "sweet",
    tasting_notes: "Pale yellow with an aroma of honeysuckle flower, and flavors of honey and dried apricot.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 7,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-stags-white",
    winery_id: "winery-arrington",
    name: "Stag's White",
    slug: "arrington-stags-white",
    varietal: "Chardonnay, Vidal Blanc, Albariño & Viognier",
    style: "white",
    tasting_notes:
      "Dry and pale golden yellow, with aromas of honey and white peach, and flavors of green apple, white nectarine, and Meyer lemon.",
    food_pairing: "Fish, chicken, salads, creamy pastas, or ceviche",
    sold_out: false,
    active: true,
    sort_order: 8,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-sparkle-blanc",
    winery_id: "winery-arrington",
    name: "Sparkle Blanc",
    slug: "arrington-sparkle-blanc",
    varietal: "Sparkling White Blend",
    style: "sparkling",
    tasting_notes: "Classic, crisp, and dry, with notes of flowers, Asian pears, lemon, and green apple.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 9,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-firefly-rose",
    winery_id: "winery-arrington",
    name: "Firefly Rosé",
    slug: "arrington-firefly-rose",
    varietal: "Rosé Blend",
    style: "rose",
    tasting_notes: "Dry but fruit-forward, with a fresh strawberry aroma and flavors of white cherry and lime zest.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 10,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-sparkle-rose",
    winery_id: "winery-arrington",
    name: "Sparkle Rosé",
    slug: "arrington-sparkle-rose",
    varietal: "Sparkling Rosé",
    style: "sparkling",
    tasting_notes:
      "Refreshing, fruit-forward, and dry, with a strawberry-rhubarb jam aroma and flavors of cherry and lime.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 11,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-russell-merlot",
    winery_id: "winery-arrington",
    name: "Russell Merlot",
    slug: "arrington-russell-merlot",
    varietal: "Merlot",
    style: "red",
    tasting_notes: "Dark ruby in color, with a juicy blackberry flavor.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 12,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-pinot-noir",
    winery_id: "winery-arrington",
    name: "Pinot Noir",
    slug: "arrington-pinot-noir",
    varietal: "Pinot Noir & Noiret",
    style: "red",
    tasting_notes:
      "Medium-bodied and dry, with aromas of black tea and earthy spice, and flavors of black pepper, black raspberry, and wild herbs.",
    food_pairing: "Herb-crusted lamb, roast duck, roasted chicken, charcuterie, or mushroom risotto",
    sold_out: false,
    active: true,
    sort_order: 13,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-petite-noir",
    winery_id: "winery-arrington",
    name: "Petite Noir",
    slug: "arrington-petite-noir",
    varietal: "Pinot Noir-Style Red Blend",
    style: "red",
    tasting_notes:
      "Light-bodied and elegant, with aromas of cherry cola and baking spices, and flavors of raspberry pie and vanilla oak.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 14,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-encore",
    winery_id: "winery-arrington",
    name: "Encore",
    slug: "arrington-encore",
    varietal: "Estate Chambourcin",
    style: "sweet",
    tasting_notes:
      "Rich and Port-style, very dark ruby, with an aroma of brown sugar and butterscotch, and flavors of Luxardo cherries and sweet brown butter.",
    food_pairing: "Blue cheese or chocolate desserts",
    sold_out: false,
    active: true,
    sort_order: 15,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-blackberry",
    winery_id: "winery-arrington",
    name: "Blackberry",
    slug: "arrington-blackberry",
    varietal: "Marion Blackberry",
    style: "sweet",
    tasting_notes:
      "Aromas of blackberry cobbler and blackberry preserves, with a rich blackberry flavor and a long, sweet finish.",
    food_pairing: "Chocolate desserts or vanilla bean ice cream",
    sold_out: false,
    active: true,
    sort_order: 16,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-arrington-sweet-blues",
    winery_id: "winery-arrington",
    name: "Sweet Blues",
    slug: "arrington-sweet-blues",
    varietal: "Blueberry & Blackberry Blend",
    style: "sweet",
    tasting_notes: "Dark purple, with a blueberry jam aroma and flavors of juicy, tart blackberries.",
    food_pairing: "Cheesecake or grilled pork tenderloin",
    sold_out: false,
    active: true,
    sort_order: 17,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-grinders-switch-cou-rouge",
    winery_id: "winery-grinders-switch",
    name: "Cou Rouge",
    slug: "grinders-switch-cou-rouge",
    varietal: "Blush Blend",
    style: "sweet",
    tasting_notes:
      "A bright, fruity blush wine with a gentle touch of tartness — refreshingly crisp on warm days.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 6,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-grinders-switch-cran-merry",
    winery_id: "winery-grinders-switch",
    name: "Cran-Merry",
    slug: "grinders-switch-cran-merry",
    varietal: "Cranberry Blend",
    style: "sweet",
    tasting_notes: "Bursts with bright cranberry flavor, balanced between tartness and sweetness.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 7,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-grinders-switch-the-general-1",
    winery_id: "winery-grinders-switch",
    name: "The General 1",
    slug: "grinders-switch-the-general-1",
    varietal: "Estate Carlos Muscadine",
    style: "sweet",
    tasting_notes: "A sweet, white estate-grown muscadine wine.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 8,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-grinders-switch-the-general-2",
    winery_id: "winery-grinders-switch",
    name: "The General 2",
    slug: "grinders-switch-the-general-2",
    varietal: "Estate Noble Muscadine",
    style: "sweet",
    tasting_notes: "A sweet, earthy red muscadine wine with a thick mouthfeel and floral notes.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 9,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-grinders-switch-marathon",
    winery_id: "winery-grinders-switch",
    name: "Marathon",
    slug: "grinders-switch-marathon",
    varietal: "Elderberry",
    style: "sweet",
    tasting_notes: "A sweet red elderberry wine.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 10,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "wine-pickers-creek-moondance",
    winery_id: "winery-pickers-creek",
    name: "Moondance",
    slug: "pickers-creek-moondance",
    varietal: "Muscat",
    style: "sweet",
    tasting_notes:
      "A sweet white wine with a subtle honeysuckle aroma and undertones of citrus, pear, and honey.",
    food_pairing: null,
    sold_out: false,
    active: true,
    sort_order: 6,
    created_at: "2026-01-01T00:00:00.000Z",
  },
];

/**
 * Seasonal hour breakdowns. Only Arrington Vineyards publishes a detailed
 * seasonal schedule; the other three wineries don't have public seasonal
 * data yet, so they fall back to their single `hours` text field until
 * seasonal rows are added for them via the admin dashboard.
 */
export const SEED_WINERY_HOURS: WineryHours[] = [
  {
    id: "hours-arrington-peak",
    winery_id: "winery-arrington",
    label: "April – October",
    start_month: 4,
    end_month: 10,
    hours_text: "Mon–Thu 11am–8pm · Fri 11am–9pm · Sat 11am–8pm · Sun 12pm–8pm",
    sort_order: 1,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "hours-arrington-latefall",
    winery_id: "winery-arrington",
    label: "November – December",
    start_month: 11,
    end_month: 12,
    hours_text: "Mon–Sat 11am–8pm · Sun 12pm–6pm",
    sort_order: 2,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "hours-arrington-winter",
    winery_id: "winery-arrington",
    label: "January – February",
    start_month: 1,
    end_month: 2,
    hours_text: "Mon–Sat 11am–6pm · Sun 12pm–6pm",
    sort_order: 3,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "hours-arrington-march",
    winery_id: "winery-arrington",
    label: "March",
    start_month: 3,
    end_month: 3,
    hours_text: "Mon–Thu 11am–7pm · Fri–Sat 11am–8pm · Sun 12pm–7pm",
    sort_order: 4,
    created_at: "2026-01-01T00:00:00.000Z",
  },
];

export const SEED_WINERY_EVENTS: WineryEvent[] = [
  {
    id: "event-arrington-livemusic",
    winery_id: "winery-arrington",
    title: "Live Music on the Lawn",
    description: "Bring a blanket and settle in among the vines for an evening of local live music.",
    event_date: "2026-09-05",
    event_time: "5:00 PM – 8:00 PM",
    source_url: "https://arringtonvineyards.com",
    created_at: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "event-arrington-foodtruck",
    winery_id: "winery-arrington",
    title: "Food Truck Friday",
    description: "A rotating local food truck sets up on the lawn for the evening.",
    event_date: "2026-09-11",
    event_time: "4:00 PM – 8:00 PM",
    source_url: "https://arringtonvineyards.com",
    created_at: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "event-arrington-yoga",
    winery_id: "winery-arrington",
    title: "Yoga in the Vines",
    description: "A gentle morning flow among the rows, followed by a tasting.",
    event_date: "2026-09-19",
    event_time: "9:00 AM – 10:30 AM",
    source_url: "https://arringtonvineyards.com",
    created_at: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "event-woodfeather-harvest",
    winery_id: "winery-woodfeather",
    title: "Harvest Weekend",
    description: "Tour the vineyard during harvest and taste this year's first press straight from the tank.",
    event_date: "2026-09-12",
    event_time: "11:00 AM – 5:00 PM",
    source_url: "https://woodfeatherfarm.com",
    created_at: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "event-grinders-newrelease",
    winery_id: "winery-grinders-switch",
    title: "New Release Tasting Night",
    description: "First pour of the newest vintage, straight off the bottling line.",
    event_date: "2026-09-06",
    event_time: "6:00 PM – 9:00 PM",
    source_url: "https://gswinery.com",
    created_at: "2026-08-16T12:00:00.000Z",
  },
];

export const SEED_REWARD_TIERS: RewardTier[] = [
  {
    id: "reward-tier-first-pour",
    label: "First Pour",
    points_required: 75,
    discount_percent: 10,
    choice_options: null,
    birthday_only: false,
    sort_order: 1,
    active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "reward-tier-trail-blazer",
    label: "Trail Blazer",
    points_required: 150,
    discount_percent: 15,
    choice_options: null,
    birthday_only: false,
    sort_order: 2,
    active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "reward-tier-estate-insider",
    label: "Estate Insider",
    points_required: 250,
    discount_percent: 20,
    choice_options: null,
    birthday_only: false,
    sort_order: 3,
    active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "reward-tier-sommeliers-choice",
    label: "Sommelier's Choice",
    points_required: 400,
    discount_percent: 35,
    choice_options: ["35% off your next purchase", "A complimentary tasting for two"],
    birthday_only: false,
    sort_order: 4,
    active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "reward-tier-birthday",
    label: "Happy Birthday!",
    points_required: 0,
    discount_percent: 10,
    choice_options: null,
    birthday_only: true,
    sort_order: 99,
    active: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
];
